server:
  port: 8070
spring:
  datasource:
    url: jdbc:mysql://ec2-3-1-59-8.ap-southeast-1.compute.amazonaws.com:3306/sims
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwt-set-uri: none
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

